# Tensors

In [3]:
import torch
import numpy as np

In [4]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [5]:
data_1 = np.array(data)
x_np = torch.from_numpy(data_1)
x_np

tensor([[1, 2],
        [3, 4]])

In [6]:
x_ones = torch.ones_like(x_data)
print(x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.0939, 0.6433],
        [0.7242, 0.0253]])


In [7]:
shape = (2,3,4)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[[0.2604, 0.8105, 0.1839, 0.1181],
         [0.5847, 0.9090, 0.7069, 0.6331],
         [0.6652, 0.0851, 0.4494, 0.7683]],

        [[0.5360, 0.4562, 0.5078, 0.1292],
         [0.0694, 0.6516, 0.8606, 0.2998],
         [0.3745, 0.6631, 0.9392, 0.0753]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [8]:
tensor = torch.rand(3,4)

print("Shape:\t\t", tensor.shape)
print("Datatype:\t", tensor.dtype)
print("Stored on:\t", tensor.device)

Shape:		 torch.Size([3, 4])
Datatype:	 torch.float32
Stored on:	 cpu


Many Tensor operations are described on pytorch documentation [here](https://pytorch.org/docs/stable/torch.html)

In [9]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print("Device tensor is stored on: {tensor.device}")
print(torch.cuda.is_available())


False


In [10]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [15]:
join = torch.cat([tensor, tensor, tensor], dim=1)
print(join)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [17]:
tensor2 = torch.rand((4,4))
tensor2

tensor([[0.3084, 0.3355, 0.6233, 0.1487],
        [0.7535, 0.4721, 0.4098, 0.4735],
        [0.9057, 0.2585, 0.0087, 0.0497],
        [0.3814, 0.0557, 0.8082, 0.1733]])

In [19]:
mult = tensor.mul(tensor2)
mult

tensor([[0.3084, 0.0000, 0.6233, 0.1487],
        [0.7535, 0.0000, 0.4098, 0.4735],
        [0.9057, 0.0000, 0.0087, 0.0497],
        [0.3814, 0.0000, 0.8082, 0.1733]])

In [21]:
into = tensor * tensor2
into

tensor([[0.3084, 0.0000, 0.6233, 0.1487],
        [0.7535, 0.0000, 0.4098, 0.4735],
        [0.9057, 0.0000, 0.0087, 0.0497],
        [0.3814, 0.0000, 0.8082, 0.1733]])